module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        app: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          muted: 'var(--color-surface-muted)',
          line: 'var(--color-line)',
          'line-strong': 'var(--color-line-strong)',
          text: 'var(--color-text)',
          'text-soft': 'var(--color-text-soft)',
          'text-muted': 'var(--color-text-muted)',
        },
        brand: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          soft: 'var(--color-primary-soft)',
          border: 'var(--color-primary-border)',
        },
        status: {
          success: 'var(--color-success)',
          'success-soft': 'var(--color-success-soft)',
          warning: 'var(--color-warning)',
          'warning-soft': 'var(--color-warning-soft)',
          danger: 'var(--color-danger)',
          'danger-soft': 'var(--color-danger-soft)',
        },
        ui: {
          canvas: 'var(--ui-canvas)',
          'canvas-subtle': 'var(--ui-canvas-subtle)',
          surface: 'var(--ui-surface)',
          raised: 'var(--ui-surface-raised)',
          muted: 'var(--ui-surface-muted)',
          ink: 'var(--ui-ink)',
          'ink-soft': 'var(--ui-ink-soft)',
          'ink-muted': 'var(--ui-ink-muted)',
          line: 'var(--ui-line)',
          'line-strong': 'var(--ui-line-strong)',
          primary: 'var(--ui-primary)',
          'primary-hover': 'var(--ui-primary-hover)',
          'primary-soft': 'var(--ui-primary-soft)',
        },
      },
      fontFamily: {
        display: ['var(--font-display)'],
        sans: ['var(--font-sans)'],
        ui: ['var(--ui-font-sans)'],
      },
      borderRadius: {
        control: 'var(--radius-control)',
        panel: 'var(--radius-panel)',
        ui: 'var(--ui-radius-md)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        soft: 'var(--shadow-soft)',
        'ui-xs': 'var(--ui-shadow-xs)',
        'ui-sm': 'var(--ui-shadow-sm)',
        'ui-md': 'var(--ui-shadow-md)',
        'ui-lg': 'var(--ui-shadow-lg)',
      },
      transitionDuration: {
        '400': '400ms',
      },
    },
  },
  plugins: [],
};
